let METHODS = {KARACHI:            {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 18},
               ISNA:               {fajr_angle: 15,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 15},
               MWL:                {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17},
               MAKKAH:             {fajr_angle: 18.5, magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: true,  isha_val: 90},
               EGYPT:              {fajr_angle: 19.5, magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17.5},
               CUSTOM:             {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17},
               QATAR:              {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: true,  isha_val: 90},
               ALGERIA:            {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 3, isha_is_minutes: false, isha_val: 17},
               JORDAN:             {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 18},
               KUWAIT:             {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17.5},
               ENGLAND_BIRMINGHAM: {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17},
               ENGLAND_LONDON:     {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17},
               GERMANY_MUNCHEN:    {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17},
               GERMANY_AACHEN:     {fajr_angle: 18,   magrib_is_minutes: true, magrib_val: 0, isha_is_minutes: false, isha_val: 17}};
